Traigamos varios indicadores e indices de Perú:

<iframe width="800" height="600" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRIELLZGB7UZfNMSHmPExFW6BsCwjWvCcNJV4uvjRd9Tnwq0DqveCBOhJhKwWaRxtPedAxrI6rHY9Ps/pubhtml?widget=true&amp;headers=false"></iframe>

## 1. Regresión Ordinal

```{r carga}
link='https://docs.google.com/spreadsheets/d/e/2PACX-1vRIELLZGB7UZfNMSHmPExFW6BsCwjWvCcNJV4uvjRd9Tnwq0DqveCBOhJhKwWaRxtPedAxrI6rHY9Ps/pub?gid=550147750&single=true&output=csv' 

perudat=read.csv(link, stringsAsFactors = F)
names(perudat)
```

Creemos una **variable dependiente ordinal** a partir del indice IDH:

```{r crea_recodifica}
niveles=c('muy baja','baja','media',"alta",'muy alta')

perudat$IDHord=cut(perudat$IDH,
                    breaks = length(niveles),
                    labels = niveles,
                    ordered_result = T)
```

```{r subset}
# podemos querer explicar el nivel de IDH
# 1-segun cada componente del IDE menos educacion
# 2-estar en la costa
sub1=c("IDHord","identidad",  "salud","educacion","saneamient","electrific","costa")
reg1Data=perudat[,sub1]
names(reg1Data)
```


```{r exploraCAT_uni}
reg1Data$costa <- as.factor(reg1Data$costa)
table(reg1Data$costa)
```

```{r}
library("oglmx")
modelOrd=ologit.reg(IDHord ~ .,
                  data = reg1Data)
summary(modelOrd)
```

```{r}
(modelOrd_M=margins.oglmx(modelOrd,ascontinuous = TRUE))
```


## 2. Regresión Beta

Veamos una numérica porcentual:

```{r}
# como se comporta la mortalidad?
summary(perudat$mortalidad)
```

Transformemosla en (0,1):

```{r}
perudat$mortalidad=perudat$mortalidad/100
```

```{r}
library(betareg)
#VD:mortalidad
#VIs:desnutrici, percapitaf, salud, saneamient, analfa
#VCs:población
sub2=c('mortalidad','desnutrici', 'percapitaf', 'salud', 'saneamient', 'analfa','pob')
reg2Data=perudat[,sub2]
modelBeta=betareg(mortalidad~.,data=reg2Data)
summary(modelBeta)
```

<!---
https://rcompanion.org/handbook/J_02.html
--->
## Parte 3. Regresión y variables latentes:

Si quisieramos demostrar la hipótesis que el IDH depende del IDH y de la ubicación de la provincia:

```{r}
modelo= 
        'ideL =~ identidad + salud + educacion + saneamient + electrific
        idhL =~ esperanza + secundaria + educa +percapitaf
        vulL =~ fecundidad + desnutrici + mortalidad

        # regresiones
        idhL ~ ideL + vulL'
```




```{r}
library(lavaan)

# 2. Calculos

regLat<-sem(modelo, data=perudat)#, fixed.x=FALSE)

# 3. Resultados

summary(regLat, standardized=TRUE)
```

```{r}

library(semPlot)

semPaths(regLat ,layout='tree2',whatLabels = 'std')

```
```{r}
modelo2= 
        'ideL =~ identidad + salud + educacion + saneamient + electrific
        idhL =~ esperanza + secundaria + educa +percapitaf
        vulL =~ fecundidad + desnutrici + mortalidad

        # regresiones
        idhL ~ ideL
        ideL ~ vulL'

# 2. Calculos

regLat2<-sem(modelo2, data=perudat)#, fixed.x=FALSE)


semPaths(regLat2 ,layout='tree2',whatLabels = 'std')

```

